IRIS = read.csv("iris.data" , header = FALSE)
colnames(IRIS) = c("SepalLength" ,"SepalWidth","PetalLength","PetalWidth" ,"Class")
mean(IRIS$SepalLength)
mean(IRIS$SepalWidth)
mean(IRIS$PetalLength)
mean(IRIS$PetalWidth)
sd(IRIS$SepalLength)
sd(IRIS$SepalWidth)
sd(IRIS$PetalLength)
sd(IRIS$PetalWidth)
IRIS_Setosa = subset(IRIS, Class == "Iris-setosa")
mean (IRIS_Setosa$SepalLength)
mean (IRIS_Setosa$SepalWidth)
mean (IRIS_Setosa$PetalLength)
mean (IRIS_Setosa$PetalWidth)
sd (IRIS_Setosa$SepalLength)
sd (IRIS_Setosa$SepalWidth)
sd (IRIS_Setosa$PetalLength)
sd (IRIS_Setosa$PetalWidth)
IRIS_Virginica = subset(IRIS, Class == "Iris-virginica")
mean (IRIS_Virginica$SepalLength)
mean (IRIS_Virginica$SepalWidth)
mean (IRIS_Virginica$PetalLength)
mean (IRIS_Virginica$PetalWidth)
sd (IRIS_Virginica$SepalLength)
sd (IRIS_Virginica$SepalWidth)
sd (IRIS_Virginica$PetalLength)
sd (IRIS_Virginica$PetalWidth)
IRIS_versicolor = subset (IRIS, Class == "Iris-versicolor")
mean (IRIS_versicolor$SepalLength)
mean (IRIS_versicolor$SepalWidth)
mean (IRIS_versicolor$PetalWidth)
mean (IRIS_versicolor$PetalLength)
sd (IRIS_versicolor$SepalLength)
sd (IRIS_versicolor$SepalWidth)
sd (IRIS_versicolor$PetalLength)
sd (IRIS_versicolor$PetalWidth)
boxplot (IRIS$SepalLength ~ IRIS$Class ,xlab= "Class" ,ylab= "Sepal Length", main = "Graph showing Sepal Length Distribution of Each Flower" ,col = "red")
boxplot (IRIS$SepalWidth ~ IRIS$Class ,xlab= "Class" ,ylab= "Sepal Width", main = "Graph showing Sepal Width Distribution of Each Flower" ,col = "red")
boxplot (IRIS$PetalLength ~ IRIS$Class ,xlab= "Class" ,ylab= "Petal Length", main = "Graph showing Petal Length Distribution of Each Flower" ,col = "red")
boxplot (IRIS$PetalWidth ~ IRIS$Class ,xlab= "Class" ,ylab= "Petal Width", main = "Graph showing Petal Width Distribution of Each Flower" ,col = "red")

